ThemeName="Loc-OS"
ThemeAuthor="live777"
License="GPL"
ThemeDescription="un simple tema de Loc-OS para ICEWM"
Look=flat
Gradients="menubg.xpm menusel.xpm switchbg.xpm taskbarbg.xpm dialogbg.xpm taskbuttonbg.xpm taskbuttonactive.xpm taskbuttonminimized.xpm buttonA.xpm buttonI.xpm toolbuttonbg.xpm workspacebuttonbg.xpm workspacebuttonactive.xpm menubg.xpm taskbuttonactive.xpm menusel.xpm titleIB.xpm titleAB.xpm titleAS.xpm titleIS.xpm"
RolloverButtonsSupported=1
TitleButtonsLeft=""
TitleButtonsRight="xmi"
TitleBarCentered=1
TitleBarHeight=18
BorderSizeX=1
BorderSizeY=1
CornerSizeX=0
CornerSizeY=0
DlgBorderSizeX=0
DlgBorderSizeY=0
ColorNormalTitleBarText="#c0c0c0"
ColorActiveTitleBarText="#ffffff"
ColorNormalButton="#000000"
ColorNormalButtonText="#ffffff"
ColorActiveButton="#000000"
ColorActiveButtonText="#FFFFFF"
ColorActiveBorder=""
ColorNormalBorder=""
ColorDialog="#000000"
ColorListBox="#000000"
ColorListBoxText="#ffffff"
ColorListBoxSelection="#000000"
ColorListBoxSelectionText="#ffffff"
ColorScrollBar="#000000"
ColorScrollBarArrow="#000000"
ColorScrollBarSlider="#000000"
ColorLabel="#000000"
ColorLabelText="#ffffff"
ColorNormalMenu="#000000"
ColorActiveMenuItem="#fcda2b"
ColorNormalMenuItemText="#ffffff"
ColorActiveMenuItemText="#000000"
ColorDisabledMenuItemText="#808080"
ColorMoveSizeStatus="#000000"
ColorMoveSizeStatusText="#FFFFFF"
ColorDefaultTaskBar="#000000"
ColorNormalTaskBarApp="#000000"
ColorNormalTaskBarAppText="#ffffff"
ColorInvisibleTaskBarApp="#000000"
ColorInvisibleTaskBarAppText="#ffffff"
ColorActiveTaskBarApp="#000000"
ColorActiveTaskBarAppText="#ffffff"
ColorMinimizedTaskBarApp="#000000"
ColorMinimizedTaskBarAppText="#ffffff"
ColorNormalWorkspaceButton="#393939"
ColorActiveWorkspaceButton="#fcda2b"
ColorInput="#000000"
ColorInputText="#ffffff"
ColorClock=""
ColorClockText=""
ColorCPUStatusUser="#000000"
ColorCPUStatusSystem="#000000"
ColorCPUStatusNice="#fcda2b"
ColorCPUStatusIdle="#000000"
ColorNetSend="#fcda2b"
ColorNetReceive="#fcda2b"
ColorNetIdle="#000000"
ColorToolTip="#000000"
ColorToolTipText="#FFFFFF"
ColorMoveSizeStatus="#000000"
ColorMoveSizeStatusText="#000000"
ColorQuickSwitch="#000000"
ColorQuickSwitchText="#ffffff"
# Font Specification
TitleFontNameXft		=	sans:size=10:bold
MenuFontNameXft			=	sans:size=11
MinimizedWindowFontNameXft	=	sans:size=10:bold
ActiveButtonFontNameXft		=	sans:size=11:bold
NormalButtonFontNameXft		=	sans:size=11
ToolButtonFontNameXft		=	sans:size=11
NormalWorkspaceFontNameXft	=	sans:size=11
ActiveWorkspaceFontNameXft	=	sans:size=11
QuickSwitchFontNameXft		=	sans:size=11
ListBoxFontNameXft		=	sans:size=11
StatusFontNameXft		=	sans:size=11
ToolTipFontNameXft		=	sans:size=11
ActiveTaskBarFontNameXft	=	sans:size=11
NormalTaskBarFontNameXft	=	sans:size=11
ClockFontNameXft		=	sans:size=11
InputFontNameXft		=	sans:size=11
TaskBarClockLeds=1
MenuIconSize=24		        # Menu
SmallIconSize=24 			# Taskbar & Titlebar. Taskbar height = height of linux.xpm. Titlebar height = TitleBarHeight in *.theme
LargeIconSize=32			# Quickswitch window
HugeIconSize=48				# ?  Cannot identify what it applies to
ShowMenuButtonIcon=0			# Show application icon on menuButton
#######################################Desktop#######################################
DesktopBackgroundImage="loc-os23.png"
DesktopBackgroundColor=""
DesktopBackgroundCenter=1